services:
  nominatim:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - pg
    volumes:
      - ./nominatim-data:/nominatim-data/
    restart: on-failure

  pg:
    image: postgis/postgis:17-3.4
    env_file:
      - .env
    volumes:
      - ./pg/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/init-nominatim.sh:/docker-entrypoint-initdb.d/init-nominatim.sh
      - pg-data:/var/lib/postgresql/data/
    restart: always

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nominatim
    restart: always



volumes:
  pg-data:
