services:
  nominatim:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - pg
    volumes:
      - ./nominatim-data:/nominatim-data/
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pg:
    image: postgis/postgis:17-3.4
    env_file:
      - .env
    volumes:
      - ./pg/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/init-nominatim.sh:/docker-entrypoint-initdb.d/init-nominatim.sh
      - ./pg-data:/var/lib/postgresql/data/
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nominatim
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  syncer:
    build:
      dockerfile: syncer/Dockerfile
    env_file:
      - .env
    volumes:
      - ./nominatim-data:/nominatim-data/
    depends_on:
      - nominatim
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
