#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DROP DATABASE IF EXISTS nominatim;
    CREATE USER $USERNAME WITH SUPERUSER PASSWORD '$POSTGRES_PASSWORD';
    CREATE USER "www-data";
EOSQL